# docker image 作成前
version: "3"
services: 
    autonomy: 
        build: ./Infra/php
        volumes: 
            - ./:/var/www/Autonomy
    web:
        image: nginx:1.18-alpine
        ports: 
            - 666:80
        volumes:
            - ./:/var/www/Autonomy
            - ./Infra/nginx/default.conf:/etc/nginx/conf.d/default.conf
        working_dir: /
